### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by SubhrajitPrusty** [SubhrajitPrusty/unsplash-download#11]
- Code changed to use requests #10 , so Readme needs to be updated

**Comment by Who23** [comment]
May I take this? Just because this is my 2nd ever PR, so I'd like to give it a shot

**Comment by Who23** [comment]
Also, what exactly needs to be edited? That requests is a dependency?

**Comment by SubhrajitPrusty** [comment]
@Who23 I've updated the code to use Click module for cli.
So, installation can be done by `pip install --editable .`
And using the cli `unsplash-download --help`

**Comment by SubhrajitPrusty** [comment]
#9
