### ISSUE TITLE
Wget should not be used

### ISSUE THREAD

**Issue by 0x48piraj** [SubhrajitPrusty/unsplash-download#6]
Wget should not be used as it is platform dependent. It makes the software very dependable.

**Comment by SubhrajitPrusty** [comment]
Wget handles incomplete downloads and large files efficiently.
Since the images being downloaded are very large, using wget is better.

**Comment by Qoyyuum** [comment]
While I agree that wget is better, its just not compatible or working in Windows unless the users use something like a Linux VM or Docker that allows the use of wget. Otherwise, it will only work on Linux (not sure on Mac but I assume it works the same?)

**Comment by SubhrajitPrusty** [comment]
You can get wget for Windows [here](http://gnuwin32.sourceforge.net/packages/wget.htm)

**Comment by 0x48piraj** [comment]
Code should be minimal. That's our point. :)
